### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by EthanCloin** [EthanCloin/financial-forecast#3]
No current functionality supporting user Log Out

## Tasks
- [x] Research how log out usually works: do they keep the session cookie? 
- [x] Add Log Out to /me
- [ ] Add Log Out to navbar
- [x] Create a /logout route which redirects to /login afterward

**Comment by EthanCloin** [comment]
## Strategy
utilize HTMX attributes on a button to POST to /logout. 
that endpoint returns a 303 Redirect

### Hangup
had some confusion about how to best approach this. I was hoping for a way to just navigate the browser to /login after the POST request was finished, fully reloading the page.

I was hoping to find a way to complete that, since i thought it would be faster and simpler. However, I ultimately arrived at a strategy to replace the current page contents with the HTML response from the Redirect to /login. I accomplished this by pointing the hx-target at a wrapper div.
<img width="1085" alt="Screenshot 2024-01-10 at 8 51 29 PM" src="https://github.com/EthanCloin/financial-forecast/assets/62920769/b00219b1-2871-4639-990b-5aadce267e20">

also i'm not worrying about the navbar, not settled on the final design for the survey pages yet.
