### ISSUE TITLE
User Balances - First Data Collection Page

### ISSUE THREAD

**Issue by EthanCloin** [EthanCloin/financial-forecast#8]
# Summary
Allow user to submit information for their current account balances to construct a Net Worth

## Tasks
- [x] HTML to collect data
- [x] POST route to accept data
- [x] DB method to store and retrieve Balances

## Decisions
How should I store balances? The underlying data is a list of dicts like :

```json
{
  balances: [
      {
          name: "checking",
          balance: 1000.93
      },
      {
          name: "saving",
          balance: 4000
      },
      {
          name: "emergency",
          balance: 200.44
      },
      {
          name: "investments",
          balance: 0
      }
  ]
}
```
current datastore is json form, i can probably just add balances, networth, netincome, debts as properties on the user. 
there is no expectation for a large quantity of data here.

**Comment by EthanCloin** [comment]
thinking about how i want to structure the Q + A portions of this app.

i should make a consistent pattern here. i need to support all four inquiries: balances, income, spending, debt.

user balances can include up to four values. each represents a different kind of account, but all will include a `name` and `balance` value. 

1. i could have a single page where i have a purpose summary for each account type. showing one at a time and replacing the summary and input fields after user hits 'next'. 
2. i could have all three input fields there with the label including an ℹ️ that shows summary text on hover (click on mobile)

option 2 seems cleaner to me and fewer interactions to worry about. 

<img width="658" alt="Screenshot 2024-01-20 at 1 12 40 PM" src="https://github.com/EthanCloin/financial-forecast/assets/62920769/74bdd54f-7556-4001-8e79-bd5752299372">
